version: '3.8'  

services:
  facial-recognition-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile  
    volumes:
      - .:/app  
    ports:
      - "8000:8000"
    environment:
      - ENV_VAR=.env
    command: ["uvicorn", "main:app", "--reload", "--ssl-certfile", "/app/agrariacoopbr.cert", "--ssl-keyfile", "/app/agrariacoopbr.key"]
